'use client'

import { useEffect, useState } from 'react'
import { ArrowDown, ArrowUpRight, BarChart3, Check, ChevronRight, CircleAlert, Clock3, ExternalLink, Eye, Landmark, LineChart, Newspaper, Scale, Settings2, Sparkles, X } from 'lucide-react'
import type { DailyData } from '@/lib/daily-data'
import { AFFILIATE_CONFIG, formatMoney, formatPercent } from '@/lib/daily-data'

const cn = (...classes: Array<string | false | null | undefined>) => classes.filter(Boolean).join(' ')
const tone = (direction: string) => direction === 'positive' ? 'text-positive' : direction === 'negative' ? 'text-negative' : 'text-warning'

export function DailyHero({ data }: { data: DailyData }) {
  const { market } = data
  return <section className="hero-shell reveal">
    <div className="eyebrow"><span className="brand-mark">₿</span><span>Bitcoin Hoy</span><span className="eyebrow-rule" /></div>
    <div className="hero-copy"><p className="kicker">Tu lectura diaria de Bitcoin</p><h1>La edición de<br /><em>hoy.</em></h1><p className="date-line">Lunes, 7 de septiembre <span>·</span> Actualizado hace 12 min</p></div>
    <div className="hero-market"><span className="price-label">BTC / USD</span><strong className="hero-price">{formatMoney(market.price)}</strong><div className="hero-change"><span className={cn('change-pill', market.change24h != null && market.change24h >= 0 ? 'positive-bg' : 'negative-bg')}>{formatPercent(market.change24h)}</span><span>en las últimas 24h</span></div></div>
    <div className="hero-stats">{[['Market Cap', formatMoney(market.marketCap, true)], ['Volumen 24h', formatMoney(market.volume24h, true)], ['Dominancia', market.dominance == null ? 'Sin datos' : `${market.dominance.toFixed(2)}%`], ['Fear & Greed', market.fearGreed == null ? 'Sin datos' : `${market.fearGreed} · ${market.fearGreedLabel}`]].map(([label, value]) => <div key={label}><span>{label}</span><b>{value}</b></div>)}</div>
    <a href="#edicion" className="scroll-cue"><span>↓</span> La edición de hoy</a>
  </section>
}

export function CatalystCard({ catalyst }: { catalyst: DailyData['catalyst'] }) {
  if (!catalyst) return <section className="section-block empty-block"><p className="section-label">Catalizador principal</p><p>Sin catalizador disponible.</p></section>
  return <section className="catalyst-card reveal"><div className="section-label accent-label"><Sparkles size={14} /> Catalizador principal</div><a href={catalyst.url || '#'} className="catalyst-title">{catalyst.title}<ArrowUpRight className="inline-icon" /></a><div className="meta-line"><span>{catalyst.source}</span><span>·</span><span>{catalyst.ago || 'Sin hora'}</span><ExternalLink size={13} /></div></section>
}

export function BitcoinChart() {
  return <div className="chart-panel"><div className="card-heading"><div><span className="section-label">Mercado</span><h2>BTC <span>· 4H</span></h2></div><span className="chart-live"><i /> Mock chart</span></div><div className="chart-area" aria-label="Gráfico simulado de Bitcoin a cuatro horas"><div className="chart-grid" /><svg viewBox="0 0 800 250" preserveAspectRatio="none" role="img" aria-label="Tendencia ascendente y retroceso reciente"><path className="chart-fill" d="M0 195 C40 184 55 168 92 176 S132 122 174 145 S225 118 258 134 S302 82 338 108 S374 150 411 123 S458 85 492 99 S526 52 567 76 S614 36 649 68 S701 80 730 49 S770 66 800 30 V250 H0 Z" /><path className="chart-line" d="M0 195 C40 184 55 168 92 176 S132 122 174 145 S225 118 258 134 S302 82 338 108 S374 150 411 123 S458 85 492 99 S526 52 567 76 S614 36 649 68 S701 80 730 49 S770 66 800 30" /></svg><div className="chart-tooltip"><span>BTC/USD</span><b>$78,764</b><small>07 Sep · 15:00</small></div></div><div className="chart-axis"><span>09:00</span><span>12:00</span><span>15:00</span><span>18:00</span></div><div className="chart-legend"><span><i className="legend-orange" /> Precio</span><span>SMA 50 <b>—</b></span><span>RSI <b>—</b></span></div></div>
}

export function MarketBias({ bias }: { bias: DailyData['bias'] }) {
  if (!bias) return <div className="bias-card"><span className="section-label">Sesgo del mercado</span><p>Sin datos</p></div>
  const isPositive = bias.key.includes('bullish'), isNegative = bias.key.includes('bearish')
  return <div className="bias-card"><div className="card-heading"><div><span className="section-label">Lectura editorial</span><h2>Sesgo del mercado</h2></div><span className={cn('bias-dot', isPositive ? 'dot-positive' : isNegative ? 'dot-negative' : 'dot-warning')} /></div><div className={cn('bias-status', isPositive ? 'status-positive' : isNegative ? 'status-negative' : 'status-warning')}><span>{isPositive ? '↑' : isNegative ? '↓' : '→'}</span> Sesgo: {bias.label}</div><div className="bias-lines"><div><span>Noticias</span><b>{bias.news || 'Sin datos'}</b></div><div><span>Institucionales</span><b>{bias.institutional || 'Sin datos'}</b></div><div><span>Traders</span><b>{bias.traders || 'Sin datos'}</b></div></div></div>
}

export function DailyChanges({ changes }: { changes: DailyData['changes'] }) {
  return <section className="section-block reveal" id="edicion"><div className="section-intro"><div><span className="section-number">01</span><h2>Qué cambió<br /><em>desde ayer</em></h2></div><p>La señal que merece tu atención antes de empezar el día.</p></div><div className="changes-list">{changes.slice(0, 3).map((item) => <div className="change-row" key={item.id}><span className="change-name">{item.label}</span><div className="comparison"><span>{item.before}</span><ChevronRight size={16} /><b>{item.after}</b></div><span className={cn('direction', tone(item.direction))}>{item.direction === 'positive' ? '↑' : item.direction === 'negative' ? '↓' : '→'}</span></div>)}</div><div className="comparison-caption"><span>AYER</span><span className="caption-line" /><span>HOY</span></div></section>
}

export function WatchToday({ watch }: { watch: DailyData['watch'] }) {
  return <section className="section-block reveal"><div className="section-intro compact"><div><span className="section-number">02</span><h2>Qué vigilar <em>hoy</em></h2></div><Eye size={20} /></div><div className="watch-grid">{watch.slice(0, 3).map((item, index) => <div className={cn('watch-item', item.importance === 'high' && 'watch-high')} key={`${item.category}-${index}`}><span className="watch-index">0{index + 1}</span><span className="watch-category">{item.category}</span><strong>{item.title}</strong><p>{item.detail}</p></div>)}</div></section>
}

const metric = (label: string, value: string, positive?: boolean) => <div className="metric"><span>{label}</span><b className={positive == null ? '' : positive ? 'text-positive' : 'text-negative'}>{value}</b></div>
export function ETFCard({ etf }: { etf: DailyData['etf'] }) { return <div className="data-card"><div className="card-heading"><div><span className="section-label"><Landmark size={14} /> Flujos institucionales</span><h2>ETF Spot Bitcoin</h2></div><ArrowUpRight size={18} /></div>{etf ? <div className="metric-grid">{metric('Último día', formatMoney(etf.lastDay, true), (etf.lastDay || 0) >= 0)}{metric('7 días', formatMoney(etf.days7, true), (etf.days7 || 0) >= 0)}{metric('30 días', formatMoney(etf.days30, true), (etf.days30 || 0) >= 0)}{metric('Cambio 30D', formatPercent(etf.change30d, 1), (etf.change30d || 0) >= 0)}</div> : <p>Sin datos</p>}</div> }
export function DerivativesCard({ derivatives }: { derivatives: DailyData['derivatives'] }) { return <div className="data-card"><div className="card-heading"><div><span className="section-label"><Settings2 size={14} /> Posicionamiento</span><h2>Derivados BTC</h2></div><BarChart3 size={18} /></div>{derivatives ? <div className="metric-grid">{metric('Funding', derivatives.funding == null ? 'Sin datos' : `${derivatives.funding.toFixed(4)}%`)}{metric('Open Interest', formatMoney(derivatives.openInterest, true))}{metric('Long / Short', derivatives.longPct == null || derivatives.shortPct == null ? 'Sin datos' : `${derivatives.longPct}% / ${derivatives.shortPct}%`)}{metric('Liquidaciones 24h', formatMoney(derivatives.liquidations24h, true))}</div> : <p>Sin datos</p>}</div> }

export function SecondaryNews({ news }: { news: DailyData['news'] }) { return <section className="section-block news-section reveal"><div className="section-intro compact"><div><span className="section-number">03</span><h2>Para completar<br /><em>el día</em></h2></div><Newspaper size={20} /></div><div className="news-list">{news.slice(0, 2).map((item, index) => <a href={item.url || '#'} className="news-item" key={`${item.title}-${index}`}><div><span>{item.source} <i>·</i> {item.ago || 'Sin hora'}</span><h3>{item.title}</h3></div><ArrowUpRight size={18} /></a>)}</div></section> }

export function AffiliateModal() { const [open, setOpen] = useState(false); useEffect(() => { const key = 'bitcoin-hoy-affiliate'; const raw = localStorage.getItem(key); const state = raw ? JSON.parse(raw) : { visitCount: 0, affiliateDismissals: 0 }; state.visitCount += 1; localStorage.setItem(key, JSON.stringify(state)); const timer = window.setTimeout(() => { if (state.visitCount === 1 || state.visitCount === 3 || state.visitCount === 7) setOpen(true) }, 22000); return () => window.clearTimeout(timer) }, []); const close = () => { const raw = localStorage.getItem('bitcoin-hoy-affiliate'); const state = raw ? JSON.parse(raw) : {}; localStorage.setItem('bitcoin-hoy-affiliate', JSON.stringify({ ...state, affiliateDismissals: (state.affiliateDismissals || 0) + 1, lastAffiliateShown: Date.now() })); setOpen(false) }; if (!open) return null; return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="affiliate-title"><div className="affiliate-modal"><button className="modal-close" onClick={close} aria-label="Cerrar"><X size={18} /></button><div className="exchange-icon">{AFFILIATE_CONFIG.EXCHANGE_IMAGE}</div><span className="section-label">Una recomendación de Bitcoin Hoy</span><h2 id="affiliate-title">¿Todavía no tienes exchange?</h2><p>Opera Bitcoin con <strong>{AFFILIATE_CONFIG.EXCHANGE_NAME}</strong> y obtén los beneficios de nuestro código.</p><a href={AFFILIATE_CONFIG.AFFILIATE_URL} className="primary-cta" onClick={() => { close(); localStorage.setItem('bitcoin-hoy-affiliate-clicked', 'true') }}>Crear una cuenta <ArrowUpRight size={16} /></a><button className="secondary-cta" onClick={close}>Ahora no</button><small>Patrocinado · Podemos recibir una comisión si te registras mediante este enlace.</small></div></div> }

export function Footer() { return <footer><div className="footer-brand"><span className="brand-mark">₿</span><strong>Bitcoin Hoy</strong></div><p>Información educativa. No constituye asesoramiento financiero.</p><div className="sources"><span>Fuentes</span><span>CoinGecko</span><span>Xoomar</span><span>Alternative.me</span><span>CoinDesk</span><span>Cointelegraph</span><span>TradingView</span></div></footer> }
